
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - VITE_DB_HOST=db
      - VITE_DB_PORT=3306
      - VITE_DB_USER=ideauser
      - VITE_DB_PASSWORD=ideapass
      - VITE_DB_NAME=ideavote
    depends_on:
      - db
  
  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=ideavote
      - MYSQL_USER=ideauser
      - MYSQL_PASSWORD=ideapass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mariadb_data:
