// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bipiwqdnwnuxgwfpyarh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpcGl3cWRud251eGd3ZnB5YXJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNDU3NTYsImV4cCI6MjA1NTcyMTc1Nn0.s3D1MXISEBna0aRNstsR5tWCyFIFeNbFpPZs5glC9Mk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);